language: java
jdk: openjdk8

git update-index --chmod=+x gradlew

before_install:
 - chmod +x gradlew
 - gradle wrapper --gradle-version 4.2
script:
  - ./gradlew clean build -i --continue
