insert into account (id, locked, code, name, api_user_id, status_id) values (1, 1, 7, 'Mat Lam Tam', 50, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (2, 1, 2, 'Flowdesk', 86, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (3, 0, 2, 'Fintone', 93, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (4, 1, 10, 'Cardguard', 66, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (5, 1, 10, 'Pannier', 27, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (6, 1, 10, 'Asoka', 88, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (7, 0, 9, 'Bigtax', 6, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (8, 0, 10, 'Fix San', 30, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (9, 1, 6, 'Namfix', 54, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (10, 1, 5, 'Matsoft', 58, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (11, 1, 6, 'Mat Lam Tam', 7, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (12, 1, 5, 'Solarbreeze', 49, 9);
insert into account (id, locked, code, name, api_user_id, status_id) values (13, 0, 4, 'Voltsillam', 18, 9);
insert into account (id, locked, code, name, api_user_id, status_id) values (14, 1, 2, 'Daltfresh', 79, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (15, 0, 10, 'Tresom', 10, 5);
insert into account (id, locked, code, name, api_user_id, status_id) values (16, 0, 8, 'Home Ing', 35, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (17, 1, 3, 'Sub-Ex', 53, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (18, 1, 10, 'Regrant', 91, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (19, 1, 4, 'Home Ing', 54, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (20, 1, 8, 'Gembucket', 7, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (21, 1, 9, 'Wrapsafe', 41, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (22, 1, 4, 'Asoka', 35, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (23, 1, 8, 'Zamit', 87, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (24, 1, 7, 'Fixflex', 66, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (25, 1, 8, 'Bytecard', 39, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (26, 1, 5, 'Subin', 92, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (27, 0, 8, 'Cardguard', 88, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (28, 1, 5, 'Tres-Zap', 54, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (29, 0, 1, 'Lotstring', 9, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (30, 0, 9, 'Transcof', 90, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (31, 1, 7, 'Span', 46, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (32, 1, 4, 'Redhold', 80, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (33, 1, 1, 'Tempsoft', 22, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (34, 0, 7, 'Zathin', 33, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (35, 1, 1, 'Bytecard', 53, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (36, 0, 4, 'Mat Lam Tam', 78, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (37, 1, 3, 'Y-Solowarm', 90, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (38, 0, 4, 'Fix San', 28, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (39, 1, 9, 'Zaam-Dox', 25, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (40, 1, 1, 'Tempsoft', 59, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (41, 1, 7, 'Tempsoft', 81, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (42, 0, 7, 'Duobam', 98, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (43, 0, 3, 'Zaam-Dox', 76, 9);
insert into account (id, locked, code, name, api_user_id, status_id) values (44, 0, 1, 'Sonsing', 5, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (45, 0, 6, 'It', 69, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (46, 1, 1, 'Transcof', 43, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (47, 0, 6, 'Redhold', 86, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (48, 1, 8, 'Keylex', 79, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (49, 1, 1, 'Viva', 92, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (50, 1, 5, 'Bytecard', 55, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (51, 1, 10, 'Bigtax', 82, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (52, 1, 10, 'Zathin', 69, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (53, 1, 2, 'Konklux', 28, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (54, 1, 8, 'Overhold', 22, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (55, 0, 6, 'Sonair', 62, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (56, 0, 6, 'Voltsillam', 8, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (57, 0, 6, 'Ventosanzap', 20, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (58, 0, 10, 'Sonair', 64, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (59, 0, 5, 'Konklab', 53, 5);
insert into account (id, locked, code, name, api_user_id, status_id) values (60, 0, 2, 'Sonair', 31, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (61, 0, 9, 'Stronghold', 77, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (62, 1, 2, 'Vagram', 69, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (63, 1, 3, 'Zathin', 22, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (64, 0, 3, 'Matsoft', 73, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (65, 1, 6, 'Quo Lux', 78, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (66, 1, 1, 'Transcof', 71, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (67, 1, 6, 'Flexidy', 66, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (68, 1, 2, 'Redhold', 80, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (69, 1, 1, 'Vagram', 29, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (70, 0, 4, 'Mat Lam Tam', 4, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (71, 0, 1, 'Domainer', 29, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (72, 1, 4, 'Viva', 26, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (73, 0, 3, 'Lotstring', 9, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (74, 0, 3, 'Span', 57, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (75, 0, 9, 'It', 69, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (76, 1, 7, 'Bitwolf', 69, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (77, 1, 9, 'Y-find', 27, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (78, 0, 1, 'Veribet', 9, 3);
insert into account (id, locked, code, name, api_user_id, status_id) values (79, 0, 6, 'Sonair', 2, 5);
insert into account (id, locked, code, name, api_user_id, status_id) values (80, 0, 8, 'Lotlux', 52, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (81, 1, 1, 'Opela', 96, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (82, 0, 2, 'Voyatouch', 24, 9);
insert into account (id, locked, code, name, api_user_id, status_id) values (83, 0, 9, 'Flowdesk', 77, 4);
insert into account (id, locked, code, name, api_user_id, status_id) values (84, 0, 5, 'Bitchip', 57, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (85, 1, 6, 'Fix San', 82, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (86, 1, 1, 'Home Ing', 92, 1);
insert into account (id, locked, code, name, api_user_id, status_id) values (87, 0, 10, 'Subin', 66, 5);
insert into account (id, locked, code, name, api_user_id, status_id) values (88, 0, 4, 'Ventosanzap', 37, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (89, 0, 6, 'Regrant', 42, 2);
insert into account (id, locked, code, name, api_user_id, status_id) values (90, 0, 8, 'Hatity', 93, 10);
insert into account (id, locked, code, name, api_user_id, status_id) values (91, 1, 1, 'Solarbreeze', 51, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (92, 0, 7, 'Pannier', 16, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (93, 1, 10, 'Tin', 54, 8);
insert into account (id, locked, code, name, api_user_id, status_id) values (94, 1, 1, 'Opela', 8, 5);
insert into account (id, locked, code, name, api_user_id, status_id) values (95, 1, 8, 'Sonair', 49, 6);
insert into account (id, locked, code, name, api_user_id, status_id) values (96, 1, 9, 'Regrant', 61, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (97, 1, 2, 'Daltfresh', 26, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (98, 1, 2, 'Tempsoft', 74, 9);
insert into account (id, locked, code, name, api_user_id, status_id) values (99, 0, 3, 'Cardify', 41, 7);
insert into account (id, locked, code, name, api_user_id, status_id) values (100, 0, 4, 'Stronghold', 59, 9);
